[tool.yapf]
indent_width = 2

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hyperwave"
authors = [{name = "Jesse Lu", email = "jesselu@spinsphotonics.com"}]
version = "v0.0.0"
description = "next-gen photonic simulation"
